export { default as Hero } from './Hero'
export { default as WhyChoose } from './WhyChoose'
export { default as OurServices } from './OurServices'
export { default as Testimonials } from './Testimonials'
export { default as CTA } from './CTA' 